export interface AsciiEntry {
  dec: number
  char: string
  description: string
}

export const asciiData: AsciiEntry[] = [
  { dec: 0, char: "NUL", description: "Null" },
  { dec: 1, char: "SOH", description: "Start of Heading" },
  { dec: 2, char: "STX", description: "Start of Text" },
  { dec: 3, char: "ETX", description: "End of Text" },
  { dec: 4, char: "EOT", description: "End of Transmission" },
  { dec: 5, char: "ENQ", description: "Enquiry" },
  { dec: 6, char: "ACK", description: "Acknowledgement" },
  { dec: 7, char: "BEL", description: "Bell" },
  { dec: 8, char: "BS", description: "Backspace" },
  { dec: 9, char: "HT", description: "Horizontal Tab" },
  { dec: 10, char: "LF", description: "Line Feed" },
  { dec: 11, char: "VT", description: "Vertical Tab" },
  { dec: 12, char: "FF", description: "Form Feed" },
  { dec: 13, char: "CR", description: "Carriage Return" },
  { dec: 14, char: "SO", description: "Shift Out" },
  { dec: 15, char: "SI", description: "Shift In" },
  { dec: 16, char: "DLE", description: "Data Link Escape" },
  { dec: 17, char: "DC1", description: "Device Control 1 (XON)" },
  { dec: 18, char: "DC2", description: "Device Control 2" },
  { dec: 19, char: "DC3", description: "Device Control 3 (XOFF)" },
  { dec: 20, char: "DC4", description: "Device Control 4" },
  { dec: 21, char: "NAK", description: "Negative Acknowledgement" },
  { dec: 22, char: "SYN", description: "Synchronous Idle" },
  { dec: 23, char: "ETB", description: "End of Transmission Block" },
  { dec: 24, char: "CAN", description: "Cancel" },
  { dec: 25, char: "EM", description: "End of Medium" },
  { dec: 26, char: "SUB", description: "Substitute" },
  { dec: 27, char: "ESC", description: "Escape" },
  { dec: 28, char: "FS", description: "File Separator" },
  { dec: 29, char: "GS", description: "Group Separator" },
  { dec: 30, char: "RS", description: "Record Separator" },
  { dec: 31, char: "US", description: "Unit Separator" },
  { dec: 32, char: " ", description: "Space" },
  { dec: 33, char: "!", description: "Exclamation mark" },
  { dec: 34, char: '"', description: "Double quote" },
  { dec: 35, char: "#", description: "Number sign" },
  { dec: 36, char: "$", description: "Dollar sign" },
  { dec: 37, char: "%", description: "Percent sign" },
  { dec: 38, char: "&", description: "Ampersand" },
  { dec: 39, char: "'", description: "Single quote" },
  { dec: 40, char: "(", description: "Left parenthesis" },
  { dec: 41, char: ")", description: "Right parenthesis" },
  { dec: 42, char: "*", description: "Asterisk" },
  { dec: 43, char: "+", description: "Plus sign" },
  { dec: 44, char: ",", description: "Comma" },
  { dec: 45, char: "-", description: "Hyphen-minus" },
  { dec: 46, char: ".", description: "Full stop" },
  { dec: 47, char: "/", description: "Solidus (slash)" },
  { dec: 48, char: "0", description: "Digit zero" },
  { dec: 49, char: "1", description: "Digit one" },
  { dec: 50, char: "2", description: "Digit two" },
  { dec: 51, char: "3", description: "Digit three" },
  { dec: 52, char: "4", description: "Digit four" },
  { dec: 53, char: "5", description: "Digit five" },
  { dec: 54, char: "6", description: "Digit six" },
  { dec: 55, char: "7", description: "Digit seven" },
  { dec: 56, char: "8", description: "Digit eight" },
  { dec: 57, char: "9", description: "Digit nine" },
  { dec: 58, char: ":", description: "Colon" },
  { dec: 59, char: ";", description: "Semicolon" },
  { dec: 60, char: "<", description: "Less-than sign" },
  { dec: 61, char: "=", description: "Equals sign" },
  { dec: 62, char: ">", description: "Greater-than sign" },
  { dec: 63, char: "?", description: "Question mark" },
  { dec: 64, char: "@", description: "Commercial at" },
  { dec: 65, char: "A", description: "Uppercase A" },
  { dec: 66, char: "B", description: "Uppercase B" },
  { dec: 67, char: "C", description: "Uppercase C" },
  { dec: 68, char: "D", description: "Uppercase D" },
  { dec: 69, char: "E", description: "Uppercase E" },
  { dec: 70, char: "F", description: "Uppercase F" },
  { dec: 71, char: "G", description: "Uppercase G" },
  { dec: 72, char: "H", description: "Uppercase H" },
  { dec: 73, char: "I", description: "Uppercase I" },
  { dec: 74, char: "J", description: "Uppercase J" },
  { dec: 75, char: "K", description: "Uppercase K" },
  { dec: 76, char: "L", description: "Uppercase L" },
  { dec: 77, char: "M", description: "Uppercase M" },
  { dec: 78, char: "N", description: "Uppercase N" },
  { dec: 79, char: "O", description: "Uppercase O" },
  { dec: 80, char: "P", description: "Uppercase P" },
  { dec: 81, char: "Q", description: "Uppercase Q" },
  { dec: 82, char: "R", description: "Uppercase R" },
  { dec: 83, char: "S", description: "Uppercase S" },
  { dec: 84, char: "T", description: "Uppercase T" },
  { dec: 85, char: "U", description: "Uppercase U" },
  { dec: 86, char: "V", description: "Uppercase V" },
  { dec: 87, char: "W", description: "Uppercase W" },
  { dec: 88, char: "X", description: "Uppercase X" },
  { dec: 89, char: "Y", description: "Uppercase Y" },
  { dec: 90, char: "Z", description: "Uppercase Z" },
  { dec: 91, char: "[", description: "Left square bracket" },
  { dec: 92, char: "\\", description: "Reverse solidus (backslash)" },
  { dec: 93, char: "]", description: "Right square bracket" },
  { dec: 94, char: "^", description: "Circumflex accent" },
  { dec: 95, char: "_", description: "Low line (underscore)" },
  { dec: 96, char: "`", description: "Grave accent" },
  { dec: 97, char: "a", description: "Lowercase a" },
  { dec: 98, char: "b", description: "Lowercase b" },
  { dec: 99, char: "c", description: "Lowercase c" },
  { dec: 100, char: "d", description: "Lowercase d" },
  { dec: 101, char: "e", description: "Lowercase e" },
  { dec: 102, char: "f", description: "Lowercase f" },
  { dec: 103, char: "g", description: "Lowercase g" },
  { dec: 104, char: "h", description: "Lowercase h" },
  { dec: 105, char: "i", description: "Lowercase i" },
  { dec: 106, char: "j", description: "Lowercase j" },
  { dec: 107, char: "k", description: "Lowercase k" },
  { dec: 108, char: "l", description: "Lowercase l" },
  { dec: 109, char: "m", description: "Lowercase m" },
  { dec: 110, char: "n", description: "Lowercase n" },
  { dec: 111, char: "o", description: "Lowercase o" },
  { dec: 112, char: "p", description: "Lowercase p" },
  { dec: 113, char: "q", description: "Lowercase q" },
  { dec: 114, char: "r", description: "Lowercase r" },
  { dec: 115, char: "s", description: "Lowercase s" },
  { dec: 116, char: "t", description: "Lowercase t" },
  { dec: 117, char: "u", description: "Lowercase u" },
  { dec: 118, char: "v", description: "Lowercase v" },
  { dec: 119, char: "w", description: "Lowercase w" },
  { dec: 120, char: "x", description: "Lowercase x" },
  { dec: 121, char: "y", description: "Lowercase y" },
  { dec: 122, char: "z", description: "Lowercase z" },
  { dec: 123, char: "{", description: "Left curly bracket" },
  { dec: 124, char: "|", description: "Vertical line" },
  { dec: 125, char: "}", description: "Right curly bracket" },
  { dec: 126, char: "~", description: "Tilde" },
  { dec: 127, char: "DEL", description: "Delete" },
]