export interface UnicodeEntry {
  char: string
  name: string
  codePoint: string
  category: string
}

export const unicodeData: UnicodeEntry[] = [
  // Latin
  { char: "A", name: "Latin Capital Letter A", codePoint: "U+0041", category: "Latin" },
  { char: "B", name: "Latin Capital Letter B", codePoint: "U+0042", category: "Latin" },
  { char: "C", name: "Latin Capital Letter C", codePoint: "U+0043", category: "Latin" },
  { char: "D", name: "Latin Capital Letter D", codePoint: "U+0044", category: "Latin" },
  { char: "E", name: "Latin Capital Letter E", codePoint: "U+0045", category: "Latin" },
  { char: "a", name: "Latin Small Letter A", codePoint: "U+0061", category: "Latin" },
  { char: "b", name: "Latin Small Letter B", codePoint: "U+0062", category: "Latin" },
  { char: "e", name: "Latin Small Letter E", codePoint: "U+0065", category: "Latin" },
  { char: "\u00C0", name: "Latin Capital Letter A with Grave", codePoint: "U+00C0", category: "Latin" },
  { char: "\u00C1", name: "Latin Capital Letter A with Acute", codePoint: "U+00C1", category: "Latin" },
  { char: "\u00C2", name: "Latin Capital Letter A with Circumflex", codePoint: "U+00C2", category: "Latin" },
  { char: "\u00C3", name: "Latin Capital Letter A with Tilde", codePoint: "U+00C3", category: "Latin" },
  { char: "\u00C4", name: "Latin Capital Letter A with Diaeresis", codePoint: "U+00C4", category: "Latin" },
  { char: "\u00C5", name: "Latin Capital Letter A with Ring Above", codePoint: "U+00C5", category: "Latin" },
  { char: "\u00C6", name: "Latin Capital Letter AE", codePoint: "U+00C6", category: "Latin" },
  { char: "\u00C7", name: "Latin Capital Letter C with Cedilla", codePoint: "U+00C7", category: "Latin" },
  { char: "\u00C8", name: "Latin Capital Letter E with Grave", codePoint: "U+00C8", category: "Latin" },
  { char: "\u00C9", name: "Latin Capital Letter E with Acute", codePoint: "U+00C9", category: "Latin" },
  { char: "\u00CA", name: "Latin Capital Letter E with Circumflex", codePoint: "U+00CA", category: "Latin" },
  { char: "\u00CB", name: "Latin Capital Letter E with Diaeresis", codePoint: "U+00CB", category: "Latin" },
  { char: "\u00CC", name: "Latin Capital Letter I with Grave", codePoint: "U+00CC", category: "Latin" },
  { char: "\u00CD", name: "Latin Capital Letter I with Acute", codePoint: "U+00CD", category: "Latin" },
  { char: "\u00CE", name: "Latin Capital Letter I with Circumflex", codePoint: "U+00CE", category: "Latin" },
  { char: "\u00CF", name: "Latin Capital Letter I with Diaeresis", codePoint: "U+00CF", category: "Latin" },
  { char: "\u00D0", name: "Latin Capital Letter Eth", codePoint: "U+00D0", category: "Latin" },
  { char: "\u00D1", name: "Latin Capital Letter N with Tilde", codePoint: "U+00D1", category: "Latin" },
  { char: "\u00D2", name: "Latin Capital Letter O with Grave", codePoint: "U+00D2", category: "Latin" },
  { char: "\u00D3", name: "Latin Capital Letter O with Acute", codePoint: "U+00D3", category: "Latin" },
  { char: "\u00D4", name: "Latin Capital Letter O with Circumflex", codePoint: "U+00D4", category: "Latin" },
  { char: "\u00D5", name: "Latin Capital Letter O with Tilde", codePoint: "U+00D5", category: "Latin" },
  { char: "\u00D6", name: "Latin Capital Letter O with Diaeresis", codePoint: "U+00D6", category: "Latin" },
  { char: "\u00D8", name: "Latin Capital Letter O with Stroke", codePoint: "U+00D8", category: "Latin" },
  { char: "\u00D9", name: "Latin Capital Letter U with Grave", codePoint: "U+00D9", category: "Latin" },
  { char: "\u00DA", name: "Latin Capital Letter U with Acute", codePoint: "U+00DA", category: "Latin" },
  { char: "\u00DB", name: "Latin Capital Letter U with Circumflex", codePoint: "U+00DB", category: "Latin" },
  { char: "\u00DC", name: "Latin Capital Letter U with Diaeresis", codePoint: "U+00DC", category: "Latin" },
  { char: "\u00DD", name: "Latin Capital Letter Y with Acute", codePoint: "U+00DD", category: "Latin" },
  { char: "\u00DE", name: "Latin Capital Letter Thorn", codePoint: "U+00DE", category: "Latin" },
  { char: "\u00DF", name: "Latin Small Letter Sharp S", codePoint: "U+00DF", category: "Latin" },
  { char: "\u00E0", name: "Latin Small Letter A with Grave", codePoint: "U+00E0", category: "Latin" },
  { char: "\u00E1", name: "Latin Small Letter A with Acute", codePoint: "U+00E1", category: "Latin" },
  { char: "\u00E9", name: "Latin Small Letter E with Acute", codePoint: "U+00E9", category: "Latin" },
  { char: "\u00F1", name: "Latin Small Letter N with Tilde", codePoint: "U+00F1", category: "Latin" },
  { char: "\u00F6", name: "Latin Small Letter O with Diaeresis", codePoint: "U+00F6", category: "Latin" },
  { char: "\u00FC", name: "Latin Small Letter U with Diaeresis", codePoint: "U+00FC", category: "Latin" },
  { char: "\u00FF", name: "Latin Small Letter Y with Diaeresis", codePoint: "U+00FF", category: "Latin" },

  // Greek
  { char: "\u0391", name: "Greek Capital Letter Alpha", codePoint: "U+0391", category: "Greek" },
  { char: "\u0392", name: "Greek Capital Letter Beta", codePoint: "U+0392", category: "Greek" },
  { char: "\u0393", name: "Greek Capital Letter Gamma", codePoint: "U+0393", category: "Greek" },
  { char: "\u0394", name: "Greek Capital Letter Delta", codePoint: "U+0394", category: "Greek" },
  { char: "\u0395", name: "Greek Capital Letter Epsilon", codePoint: "U+0395", category: "Greek" },
  { char: "\u0396", name: "Greek Capital Letter Zeta", codePoint: "U+0396", category: "Greek" },
  { char: "\u0397", name: "Greek Capital Letter Eta", codePoint: "U+0397", category: "Greek" },
  { char: "\u0398", name: "Greek Capital Letter Theta", codePoint: "U+0398", category: "Greek" },
  { char: "\u0399", name: "Greek Capital Letter Iota", codePoint: "U+0399", category: "Greek" },
  { char: "\u039A", name: "Greek Capital Letter Kappa", codePoint: "U+039A", category: "Greek" },
  { char: "\u039B", name: "Greek Capital Letter Lambda", codePoint: "U+039B", category: "Greek" },
  { char: "\u039C", name: "Greek Capital Letter Mu", codePoint: "U+039C", category: "Greek" },
  { char: "\u039D", name: "Greek Capital Letter Nu", codePoint: "U+039D", category: "Greek" },
  { char: "\u039E", name: "Greek Capital Letter Xi", codePoint: "U+039E", category: "Greek" },
  { char: "\u03A0", name: "Greek Capital Letter Pi", codePoint: "U+03A0", category: "Greek" },
  { char: "\u03A1", name: "Greek Capital Letter Rho", codePoint: "U+03A1", category: "Greek" },
  { char: "\u03A3", name: "Greek Capital Letter Sigma", codePoint: "U+03A3", category: "Greek" },
  { char: "\u03A4", name: "Greek Capital Letter Tau", codePoint: "U+03A4", category: "Greek" },
  { char: "\u03A6", name: "Greek Capital Letter Phi", codePoint: "U+03A6", category: "Greek" },
  { char: "\u03A8", name: "Greek Capital Letter Psi", codePoint: "U+03A8", category: "Greek" },
  { char: "\u03A9", name: "Greek Capital Letter Omega", codePoint: "U+03A9", category: "Greek" },
  { char: "\u03B1", name: "Greek Small Letter Alpha", codePoint: "U+03B1", category: "Greek" },
  { char: "\u03B2", name: "Greek Small Letter Beta", codePoint: "U+03B2", category: "Greek" },
  { char: "\u03B3", name: "Greek Small Letter Gamma", codePoint: "U+03B3", category: "Greek" },
  { char: "\u03B4", name: "Greek Small Letter Delta", codePoint: "U+03B4", category: "Greek" },
  { char: "\u03B5", name: "Greek Small Letter Epsilon", codePoint: "U+03B5", category: "Greek" },
  { char: "\u03B8", name: "Greek Small Letter Theta", codePoint: "U+03B8", category: "Greek" },
  { char: "\u03BB", name: "Greek Small Letter Lambda", codePoint: "U+03BB", category: "Greek" },
  { char: "\u03BC", name: "Greek Small Letter Mu", codePoint: "U+03BC", category: "Greek" },
  { char: "\u03C0", name: "Greek Small Letter Pi", codePoint: "U+03C0", category: "Greek" },
  { char: "\u03C3", name: "Greek Small Letter Sigma", codePoint: "U+03C3", category: "Greek" },
  { char: "\u03C6", name: "Greek Small Letter Phi", codePoint: "U+03C6", category: "Greek" },
  { char: "\u03C9", name: "Greek Small Letter Omega", codePoint: "U+03C9", category: "Greek" },

  // Math
  { char: "\u00B1", name: "Plus-Minus Sign", codePoint: "U+00B1", category: "Math" },
  { char: "\u00D7", name: "Multiplication Sign", codePoint: "U+00D7", category: "Math" },
  { char: "\u00F7", name: "Division Sign", codePoint: "U+00F7", category: "Math" },
  { char: "\u2248", name: "Almost Equal To", codePoint: "U+2248", category: "Math" },
  { char: "\u2260", name: "Not Equal To", codePoint: "U+2260", category: "Math" },
  { char: "\u2264", name: "Less Than or Equal To", codePoint: "U+2264", category: "Math" },
  { char: "\u2265", name: "Greater Than or Equal To", codePoint: "U+2265", category: "Math" },
  { char: "\u221E", name: "Infinity", codePoint: "U+221E", category: "Math" },
  { char: "\u2211", name: "N-Ary Summation", codePoint: "U+2211", category: "Math" },
  { char: "\u222B", name: "Integral", codePoint: "U+222B", category: "Math" },
  { char: "\u221A", name: "Square Root", codePoint: "U+221A", category: "Math" },
  { char: "\u2202", name: "Partial Differential", codePoint: "U+2202", category: "Math" },
  { char: "\u2207", name: "Nabla", codePoint: "U+2207", category: "Math" },
  { char: "\u2208", name: "Element Of", codePoint: "U+2208", category: "Math" },
  { char: "\u2209", name: "Not An Element Of", codePoint: "U+2209", category: "Math" },
  { char: "\u2200", name: "For All", codePoint: "U+2200", category: "Math" },
  { char: "\u2203", name: "There Exists", codePoint: "U+2203", category: "Math" },
  { char: "\u2282", name: "Subset Of", codePoint: "U+2282", category: "Math" },
  { char: "\u2283", name: "Superset Of", codePoint: "U+2283", category: "Math" },
  { char: "\u2229", name: "Intersection", codePoint: "U+2229", category: "Math" },
  { char: "\u222A", name: "Union", codePoint: "U+222A", category: "Math" },
  { char: "\u2227", name: "Logical And", codePoint: "U+2227", category: "Math" },
  { char: "\u2228", name: "Logical Or", codePoint: "U+2228", category: "Math" },
  { char: "\u00AC", name: "Not Sign", codePoint: "U+00AC", category: "Math" },
  { char: "\u2234", name: "Therefore", codePoint: "U+2234", category: "Math" },
  { char: "\u2235", name: "Because", codePoint: "U+2235", category: "Math" },
  { char: "\u2261", name: "Identical To", codePoint: "U+2261", category: "Math" },
  { char: "\u2245", name: "Approximately Equal To", codePoint: "U+2245", category: "Math" },
  { char: "\u2205", name: "Empty Set", codePoint: "U+2205", category: "Math" },
  { char: "\u2135", name: "Alef Symbol", codePoint: "U+2135", category: "Math" },

  // Arrows
  { char: "\u2190", name: "Leftwards Arrow", codePoint: "U+2190", category: "Arrows" },
  { char: "\u2191", name: "Upwards Arrow", codePoint: "U+2191", category: "Arrows" },
  { char: "\u2192", name: "Rightwards Arrow", codePoint: "U+2192", category: "Arrows" },
  { char: "\u2193", name: "Downwards Arrow", codePoint: "U+2193", category: "Arrows" },
  { char: "\u2194", name: "Left Right Arrow", codePoint: "U+2194", category: "Arrows" },
  { char: "\u2195", name: "Up Down Arrow", codePoint: "U+2195", category: "Arrows" },
  { char: "\u2196", name: "North West Arrow", codePoint: "U+2196", category: "Arrows" },
  { char: "\u2197", name: "North East Arrow", codePoint: "U+2197", category: "Arrows" },
  { char: "\u2198", name: "South East Arrow", codePoint: "U+2198", category: "Arrows" },
  { char: "\u2199", name: "South West Arrow", codePoint: "U+2199", category: "Arrows" },
  { char: "\u21D0", name: "Leftwards Double Arrow", codePoint: "U+21D0", category: "Arrows" },
  { char: "\u21D1", name: "Upwards Double Arrow", codePoint: "U+21D1", category: "Arrows" },
  { char: "\u21D2", name: "Rightwards Double Arrow", codePoint: "U+21D2", category: "Arrows" },
  { char: "\u21D3", name: "Downwards Double Arrow", codePoint: "U+21D3", category: "Arrows" },
  { char: "\u21D4", name: "Left Right Double Arrow", codePoint: "U+21D4", category: "Arrows" },
  { char: "\u27F5", name: "Long Leftwards Arrow", codePoint: "U+27F5", category: "Arrows" },
  { char: "\u27F6", name: "Long Rightwards Arrow", codePoint: "U+27F6", category: "Arrows" },
  { char: "\u27F7", name: "Long Left Right Arrow", codePoint: "U+27F7", category: "Arrows" },
  { char: "\u21A6", name: "Rightwards Arrow from Bar", codePoint: "U+21A6", category: "Arrows" },

  // Currency
  { char: "$", name: "Dollar Sign", codePoint: "U+0024", category: "Currency" },
  { char: "\u20AC", name: "Euro Sign", codePoint: "U+20AC", category: "Currency" },
  { char: "\u00A3", name: "Pound Sign", codePoint: "U+00A3", category: "Currency" },
  { char: "\u00A5", name: "Yen Sign", codePoint: "U+00A5", category: "Currency" },
  { char: "\u00A2", name: "Cent Sign", codePoint: "U+00A2", category: "Currency" },
  { char: "\u20B9", name: "Indian Rupee Sign", codePoint: "U+20B9", category: "Currency" },
  { char: "\u20BF", name: "Bitcoin Sign", codePoint: "U+20BF", category: "Currency" },
  { char: "\u20A9", name: "Won Sign", codePoint: "U+20A9", category: "Currency" },
  { char: "\u20A8", name: "Rupee Sign", codePoint: "U+20A8", category: "Currency" },
  { char: "\u20AB", name: "Dong Sign", codePoint: "U+20AB", category: "Currency" },
  { char: "\u20AA", name: "New Sheqel Sign", codePoint: "U+20AA", category: "Currency" },
  { char: "\u20B2", name: "Guarani Sign", codePoint: "U+20B2", category: "Currency" },
  { char: "\u20B1", name: "Peso Sign", codePoint: "U+20B1", category: "Currency" },
  { char: "\u20BA", name: "Turkish Lira Sign", codePoint: "U+20BA", category: "Currency" },
  { char: "\u20B4", name: "Hryvnia Sign", codePoint: "U+20B4", category: "Currency" },

  // Punctuation
  { char: "\u2013", name: "En Dash", codePoint: "U+2013", category: "Punctuation" },
  { char: "\u2014", name: "Em Dash", codePoint: "U+2014", category: "Punctuation" },
  { char: "\u2018", name: "Left Single Quotation Mark", codePoint: "U+2018", category: "Punctuation" },
  { char: "\u2019", name: "Right Single Quotation Mark", codePoint: "U+2019", category: "Punctuation" },
  { char: "\u201C", name: "Left Double Quotation Mark", codePoint: "U+201C", category: "Punctuation" },
  { char: "\u201D", name: "Right Double Quotation Mark", codePoint: "U+201D", category: "Punctuation" },
  { char: "\u2026", name: "Horizontal Ellipsis", codePoint: "U+2026", category: "Punctuation" },
  { char: "\u00A7", name: "Section Sign", codePoint: "U+00A7", category: "Punctuation" },
  { char: "\u00B6", name: "Pilcrow Sign", codePoint: "U+00B6", category: "Punctuation" },
  { char: "\u00A9", name: "Copyright Sign", codePoint: "U+00A9", category: "Punctuation" },
  { char: "\u00AE", name: "Registered Sign", codePoint: "U+00AE", category: "Punctuation" },
  { char: "\u2122", name: "Trade Mark Sign", codePoint: "U+2122", category: "Punctuation" },
  { char: "\u2020", name: "Dagger", codePoint: "U+2020", category: "Punctuation" },
  { char: "\u2021", name: "Double Dagger", codePoint: "U+2021", category: "Punctuation" },
  { char: "\u00B0", name: "Degree Sign", codePoint: "U+00B0", category: "Punctuation" },
  { char: "\u2032", name: "Prime", codePoint: "U+2032", category: "Punctuation" },
  { char: "\u2033", name: "Double Prime", codePoint: "U+2033", category: "Punctuation" },
  { char: "\u00AB", name: "Left-Pointing Double Angle Quotation Mark", codePoint: "U+00AB", category: "Punctuation" },
  { char: "\u00BB", name: "Right-Pointing Double Angle Quotation Mark", codePoint: "U+00BB", category: "Punctuation" },
  { char: "\u2022", name: "Bullet", codePoint: "U+2022", category: "Punctuation" },

  // Symbols
  { char: "\u2660", name: "Black Spade Suit", codePoint: "U+2660", category: "Symbols" },
  { char: "\u2661", name: "White Heart Suit", codePoint: "U+2661", category: "Symbols" },
  { char: "\u2662", name: "White Diamond Suit", codePoint: "U+2662", category: "Symbols" },
  { char: "\u2663", name: "Black Club Suit", codePoint: "U+2663", category: "Symbols" },
  { char: "\u2665", name: "Black Heart Suit", codePoint: "U+2665", category: "Symbols" },
  { char: "\u2666", name: "Black Diamond Suit", codePoint: "U+2666", category: "Symbols" },
  { char: "\u266A", name: "Eighth Note", codePoint: "U+266A", category: "Symbols" },
  { char: "\u266B", name: "Beamed Eighth Notes", codePoint: "U+266B", category: "Symbols" },
  { char: "\u263A", name: "White Smiling Face", codePoint: "U+263A", category: "Symbols" },
  { char: "\u263B", name: "Black Smiling Face", codePoint: "U+263B", category: "Symbols" },
  { char: "\u2713", name: "Check Mark", codePoint: "U+2713", category: "Symbols" },
  { char: "\u2717", name: "Ballot X", codePoint: "U+2717", category: "Symbols" },
  { char: "\u2726", name: "Black Four Pointed Star", codePoint: "U+2726", category: "Symbols" },
  { char: "\u2605", name: "Black Star", codePoint: "U+2605", category: "Symbols" },
  { char: "\u2606", name: "White Star", codePoint: "U+2606", category: "Symbols" },
  { char: "\u2640", name: "Female Sign", codePoint: "U+2640", category: "Symbols" },
  { char: "\u2642", name: "Male Sign", codePoint: "U+2642", category: "Symbols" },
  { char: "\u2625", name: "Yin Yang", codePoint: "U+2625", category: "Symbols" },
  { char: "\u262E", name: "Peace Symbol", codePoint: "U+262E", category: "Symbols" },
  { char: "\u262F", name: "Yin Yang", codePoint: "U+262F", category: "Symbols" },
  { char: "\u26A0", name: "Warning Sign", codePoint: "U+26A0", category: "Symbols" },
  { char: "\u26D4", name: "No Entry", codePoint: "U+26D4", category: "Symbols" },
  { char: "\u2708", name: "Airplane", codePoint: "U+2708", category: "Symbols" },
  { char: "\u2709", name: "Envelope", codePoint: "U+2709", category: "Symbols" },
  { char: "\u270E", name: "Lower Right Pencil", codePoint: "U+270E", category: "Symbols" },
  { char: "\u2714", name: "Heavy Check Mark", codePoint: "U+2714", category: "Symbols" },
  { char: "\u2718", name: "Heavy Ballot X", codePoint: "U+2718", category: "Symbols" },
  { char: "\u271D", name: "Latin Cross", codePoint: "U+271D", category: "Symbols" },
  { char: "\u2721", name: "Star of David", codePoint: "U+2721", category: "Symbols" },
  { char: "\u2736", name: "Six Pointed Black Star", codePoint: "U+2736", category: "Symbols" },
]

export const unicodeCategories = ["Latin", "Greek", "Math", "Arrows", "Currency", "Punctuation", "Symbols"]